### ISSUE TITLE
Error when visiting artist

### ISSUE THREAD

**Issue by arximboldi** [thieman/soundcloud.el#2]
Whenever I try to visit an artist page, either by using `a` or `s` and then hitting enter on a search result, I get the following error in `*messages*` and nothing happens:
```lisp
Contacting host: api.soundcloud.com:80
deferred error : (error "Error while resolving artist permalink, try using artist search instead")
```

Thanks!

**Comment by thieman** [comment]
Thanks for writing in. The entire library's been broken for a while now after SoundCloud introduced gzip compression into their API. The response we're getting back is now gzip'd, which Emacs's `url.el` does not handle for us.

Fix should be as easy as finding something to ungzip the request payload and rigging it into `soundcloud-get-data-from-request`.

**Comment by thieman** [comment]
@arximboldi Fix is out and should be on MELPA soon. Alternatively you could download the source and run a `package-install-from-buffer` to get the fix now. Could you please let me know whether this resolved your problem?

**Comment by arximboldi** [comment]
Wow, that was quick, thanks @thieman!

It seems to mostly work, but now I get the following error, which seems like it could be a problem of my config:

```
deferred error : (wrong-type-argument stringp (error "Don't know how to play track: (*track* (type . url) (name . \"http://ec-media.sndcdn.com/uStpD4lifNjL.128.mp3?f10880d39085a94a0418a7ef69b03d522cd6dfee9399eeb9a522029c68faba3f41fa2239aea783f058f37b727d49993de24c67e908c503cd9304bc7899b5c410e0c282d35a\"))"))
```

**Comment by arximboldi** [comment]
Just solved, the following was missing, as suggested by your Readme:

```
(emms-standard)
(emms-default-players)
```

Thanks a lot!

**Comment by thieman** [comment]
:smile: :musical_note:
